//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMODA_FRONT_HTTPS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class test1Entities : DbContext
    {
        public test1Entities()
            : base("name=test1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<about> about { get; set; }
        public virtual DbSet<banner> banner { get; set; }
        public virtual DbSet<code> code { get; set; }
        public virtual DbSet<community> community { get; set; }
        public virtual DbSet<company> company { get; set; }
        public virtual DbSet<company_class> company_class { get; set; }
        public virtual DbSet<discount> discount { get; set; }
        public virtual DbSet<discount_code> discount_code { get; set; }
        public virtual DbSet<email> email { get; set; }
        public virtual DbSet<feedback> feedback { get; set; }
        public virtual DbSet<forgetpassword> forgetpassword { get; set; }
        public virtual DbSet<hot_search> hot_search { get; set; }
        public virtual DbSet<manger> manger { get; set; }
        public virtual DbSet<member_level> member_level { get; set; }
        public virtual DbSet<membership> membership { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<news_class> news_class { get; set; }
        public virtual DbSet<ob_order> ob_order { get; set; }
        public virtual DbSet<ob_order_detail> ob_order_detail { get; set; }
        public virtual DbSet<olduser> olduser { get; set; }
        public virtual DbSet<onsale> onsale { get; set; }
        public virtual DbSet<order_> order_ { get; set; }
        public virtual DbSet<order_detail> order_detail { get; set; }
        public virtual DbSet<permission> permission { get; set; }
        public virtual DbSet<product_category> product_category { get; set; }
        public virtual DbSet<product_class> product_class { get; set; }
        public virtual DbSet<product_class1> product_class1 { get; set; }
        public virtual DbSet<product_class2> product_class2 { get; set; }
        public virtual DbSet<product_img> product_img { get; set; }
        public virtual DbSet<province> province { get; set; }
        public virtual DbSet<question> question { get; set; }
        public virtual DbSet<question_category> question_category { get; set; }
        public virtual DbSet<question_class> question_class { get; set; }
        public virtual DbSet<question_set> question_set { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<season> season { get; set; }
        public virtual DbSet<service_category> service_category { get; set; }
        public virtual DbSet<service_order> service_order { get; set; }
        public virtual DbSet<shopping> shopping { get; set; }
        public virtual DbSet<shopping_class> shopping_class { get; set; }
        public virtual DbSet<shopping_gold> shopping_gold { get; set; }
        public virtual DbSet<sizemeasure> sizemeasure { get; set; }
        public virtual DbSet<stock_detail> stock_detail { get; set; }
        public virtual DbSet<store> store { get; set; }
        public virtual DbSet<store_class> store_class { get; set; }
        public virtual DbSet<thai_currency> thai_currency { get; set; }
        public virtual DbSet<video> video { get; set; }
        public virtual DbSet<color_type> color_type { get; set; }
        public virtual DbSet<currency> currency { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<member> member { get; set; }
    }
}
