//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMODA_FRONT_HTTPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int id { get; set; }
        public System.DateTime c_time { get; set; }
        public int c_id { get; set; }
        public System.DateTime u_time { get; set; }
        public int u_id { get; set; }
        public string account { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string fb_id { get; set; }
        public string line_id { get; set; }
        public string name { get; set; }
        public System.DateTime birthday { get; set; }
        public Nullable<int> sex { get; set; }
        public string tel { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public int level { get; set; }
        public System.DateTime level_start_time { get; set; }
        public System.DateTime level_end_time { get; set; }
        public string discount_code { get; set; }
        public int feedback { get; set; }
        public int shopping_gold { get; set; }
        public string remark { get; set; }
    }
}
