//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMODA_FRONT_HTTPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ob_order
    {
        public int id { get; set; }
        public System.DateTime c_time { get; set; }
        public System.DateTime u_time { get; set; }
        public int status { get; set; }
        public string order_no { get; set; }
        public string ob_OrderNo { get; set; }
        public int OrderAmt { get; set; }
        public int Shipment { get; set; }
        public int TotalAmt { get; set; }
        public int Discount { get; set; }
        public int Balance { get; set; }
        public string ErrorMessage { get; set; }
    }
}
