//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMODA_FRONT_HTTPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_detail
    {
        public int id { get; set; }
        public System.DateTime c_time { get; set; }
        public string order_no { get; set; }
        public string p_id { get; set; }
        public string color { get; set; }
        public string size { get; set; }
        public int num { get; set; }
        public int price { get; set; }
        public string remark { get; set; }
    }
}
