//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMODA_FRONT_HTTPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_
    {
        public int id { get; set; }
        public System.DateTime c_time { get; set; }
        public System.DateTime u_time { get; set; }
        public int u_id { get; set; }
        public System.DateTime time_ { get; set; }
        public int m_id { get; set; }
        public string order_no { get; set; }
        public string ob_order_no { get; set; }
        public int total { get; set; }
        public int fare { get; set; }
        public int sum_ { get; set; }
        public int discount1 { get; set; }
        public int discount2 { get; set; }
        public int discount3 { get; set; }
        public string name_ { get; set; }
        public string tel { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public int payment_status { get; set; }
        public int pay_status { get; set; }
        public int ship_status { get; set; }
        public string remark { get; set; }
        public string PaymentRefCode { get; set; }
        public string RemittancesNo { get; set; }
        public string country { get; set; }
        public string postalCode { get; set; }
        public string state { get; set; }
        public string city { get; set; }
    }
}
