//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMODA_FRONT_HTTPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string p_id { get; set; }
        public Nullable<System.DateTime> c_time { get; set; }
        public Nullable<int> c_id { get; set; }
        public Nullable<System.DateTime> u_time { get; set; }
        public Nullable<int> u_id { get; set; }
        public Nullable<int> @switch { get; set; }
        public Nullable<int> sort { get; set; }
        public string th_name { get; set; }
        public string en_name { get; set; }
        public string ch_name { get; set; }
        public Nullable<int> @class { get; set; }
        public Nullable<int> categoryno { get; set; }
        public string categoryid1 { get; set; }
        public string categoryid2 { get; set; }
        public string producturl { get; set; }
        public string bigimage { get; set; }
        public string smallimage { get; set; }
        public string rectangleimage { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> discountedprice { get; set; }
        public string th_description { get; set; }
        public string en_description { get; set; }
        public string ch_description { get; set; }
        public string descriptionUrl { get; set; }
        public Nullable<int> stock { get; set; }
        public string collocationProduct { get; set; }
        public string sourcingCategory { get; set; }
        public string product_type { get; set; }
        public Nullable<int> season { get; set; }
        public string season1 { get; set; }
        public string sizetable { get; set; }
        public string applinks { get; set; }
        public string overseas { get; set; }
        public string remark { get; set; }
        public Nullable<byte> index_sg { get; set; }
        public string ch_sizetable { get; set; }
        public string th_sizetable { get; set; }
        public string en_sizetable { get; set; }
    }
}
