//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMODA_FRONT_HTTPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_class
    {
        public int id { get; set; }
        public System.DateTime c_time { get; set; }
        public int c_id { get; set; }
        public System.DateTime u_time { get; set; }
        public int u_id { get; set; }
        public int @switch { get; set; }
        public int sort { get; set; }
        public string name { get; set; }
        public string banner { get; set; }
        public string banner_url { get; set; }
        public string banner1 { get; set; }
        public string banner_url1 { get; set; }
        public string banner2 { get; set; }
        public string banner_url2 { get; set; }
        public string img { get; set; }
        public string img_url { get; set; }
        public string img1 { get; set; }
        public string img_url1 { get; set; }
        public string img2 { get; set; }
        public string img_url2 { get; set; }
        public string img3 { get; set; }
        public string img_url3 { get; set; }
        public string img4 { get; set; }
        public string img_url4 { get; set; }
        public int banner_action { get; set; }
        public int img_action { get; set; }
        public int index_ { get; set; }
        public string remark { get; set; }
    }
}
