//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMODA_FRONT_HTTPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sizemeasure
    {
        public int id { get; set; }
        public string en_field1 { get; set; }
        public string en_field2 { get; set; }
        public string en_field3 { get; set; }
        public string en_field4 { get; set; }
        public string en_field5 { get; set; }
        public string en_field6 { get; set; }
        public string en_field7 { get; set; }
        public string en_field8 { get; set; }
        public string th_field1 { get; set; }
        public string th_field2 { get; set; }
        public string th_field3 { get; set; }
        public string th_field4 { get; set; }
        public string th_field5 { get; set; }
        public string th_field6 { get; set; }
        public string th_field7 { get; set; }
        public string th_field8 { get; set; }
    }
}
